services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - mimir
      - loki

  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    ports:
      - "9009:9009"
    command: ["run","etc/mimir/mimir.yaml"]
    volumes:
      - ./mimir-config.yaml:/etc/mimir/mimir.yaml
  
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: ["-config.file=/etc/loki-local-config.yaml"]
    volumes:
     - ./loki-config.yaml:/etc/loki-local-config.yaml
     - ./loki-data:/loki

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "12345:12345" # for Alloy metrics or debugging
    command: ["run", "/etc/alloy/alloy-config.yaml"]
    volumes:
      - ./alloy/config.alloy:/etc/alloy/alloy-config.yaml
      - /var/log:/var/log:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  # Optional Node Exporter (if Alloy is not scraping directly)
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    restart: unless-stopped
